apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-broker-app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/amq-broker-mqtt-gitops.git
    targetRevision: HEAD
    path: argocd-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      allowEmpty: true
